### ISSUE TITLE
API Call: Get all listings

### ISSUE THREAD

**Issue by slvnwhrl** [webuko/backend#21]
This issue relates to #1 and #11.

The goal is to provide an API call that returns all available Airbnb listings. This call can be used to initialize the map. 

Proposition for the return object of the call: JSON array of objects. Each objects should at least contain the following key value pairs:

- name of listing
- longitude and latitude
- summary
- url to the picture of the listing
- price

Should there be any need for other attributes, this can be discussed here.

**Comment by slvnwhrl** [comment]
The method as implemented by 7cccc76 defines two different methods: GET and POST. The GET method returns default attributes for each listing, while the POST method allows to specify which attributes should be returned. Note that only listings will be returned that contain all the requested (or default) attributes.

**Comment by mialbu** [comment]
This issue is implemented. I close it.
