### ISSUE TITLE
API Call: Filter listings

### ISSUE THREAD

**Issue by slvnwhrl** [webuko/backend#22]
This issue relates to #10.

The goal is to provide an API call that allows filtering based on the attributes of the dataset. Additionally, it should be possible to select which attributes are returned, as discussed in #21.

The following filtering parameters should at least be implemented:
- price
- neighbourhood
- bathrooms
- bedrooms
- property_type
- room_type
- accomodates

Proposition for the return object of the call: JSON array of objects.

**Comment by mialbu** [comment]
The main filtering options are supported. I will close this issue.
