### ISSUE TITLE
Flask in production mode

### ISSUE THREAD

**Issue by slvnwhrl** [webuko/backend#31]
When the application is pushed to docker and then started using the docker-compose file for the production environment, the flask application should be run in production mode (currently in development mode). For this purpose, I suggest to refactor the application code such that a flask app can be created using the[ factory pattern](https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/). This way, it is easy to start a production web server such as waitress (see [here](https://flask.palletsprojects.com/en/1.1.x/tutorial/deploy/))

**Comment by slvnwhrl** [comment]
Commit 86ae063 applies a lot of changes:
- now the factory method is used to initiate an application
- methods (formerly in app.py) are now in a separate file (routes.py)
- methods are added via Flask's Blueprint method to an application

The factorisation allows to easily instantiate an application such that it can be run by different web servers (in development env: Flask's web server, in production env: waitress). The corresponding Dockerfile for the Flask microservice is adapted. Additionally, the production docker-compose file has been updated, too.

**Comment by mialbu** [comment]
I'll close this issue, this was done in pr #33.
